use super::*;

impl TimelineState {
    /// Seeded demo project — three tracks with synthetic audio/MIDI clips.
    /// Intended for development, screenshots, and the demo seed flag in the
    /// app entry point; never used by the real runtime default.
    pub fn demo_project() -> Self {
        let track1 = TrackState {
            listen: ListenMode::Off,
            id: "track-1".to_string(),
            name: "Audio 1".to_string(),
            track_type: TrackType::Audio,
            ara: None,
            timebase: TrackTimebase::default(),
            parent_group_id: None,
            group_collapsed: false,
            color: crate::theme::Colors::track_color_for_index(0),
            volume: volume::db_to_norm(-3.0),
            volume_effective: volume::db_to_norm(-3.0),
            volume_automation_read: true,
            pan: 0.0,
            muted: false,
            solo: false,
            armed: false,
            input_monitor: InputMonitorMode::Off,
            meter_level_l: 0.62,
            meter_level_r: 0.68,
            meter_peak_hold_l: 0.0,
            meter_peak_hold_r: 0.0,
            meter_clip: false,
            clips: vec![
                ClipState {
                    id: "clip-1".to_string(),
                    name: "vocals_dry.wav".to_string(),
                    start_beat: 1.0,
                    duration_beats: 8.0,
                    source_duration_seconds: None,
                    offset_beats: 0.0,
                    gain: 1.0,
                    clip_type: ClipType::Audio {
                        file_id: "file-vocals-dry".to_string(),
                        source_path: None,
                    },
                    muted: false,
                    audio_import: AudioImportState::Ready,
                    stretch: AudioClipStretchState::default(),
                },
                ClipState {
                    id: "clip-2".to_string(),
                    name: "vocals_harmony.wav".to_string(),
                    start_beat: 10.0,
                    duration_beats: 6.0,
                    source_duration_seconds: None,
                    offset_beats: 0.0,
                    gain: 1.0,
                    clip_type: ClipType::Audio {
                        file_id: "file-vocals-harmony".to_string(),
                        source_path: None,
                    },
                    muted: false,
                    audio_import: AudioImportState::Ready,
                    stretch: AudioClipStretchState::default(),
                },
            ],
            automation_lanes: vec![AutomationLaneState {
                id: "lane-1".to_string(),
                name: "Volume".to_string(),
                target: AutomationTarget::TrackVolume,
                enabled: true,
                visible: false,
                points: vec![
                    AutomationPoint::new(0.0, 0.8),
                    AutomationPoint::new(4.0, 0.5),
                    AutomationPoint::new(8.0, 0.8),
                ],
            }],
            lane_mode: TrackLaneMode::Clips,
            selected_automation_target: None,
            inserts: Vec::new(),
            sends: Vec::new(),
            routing: TrackRoutingState::for_track_type(TrackType::Audio),
            takes: Vec::new(),
            takes_expanded: false,
            instrument_plugin_instance_id: None,
            builtin_soundfont_player: false,
            soundfont_path: None,
            soundfont_preset: None,
            soundfont_volume: 1.0,
            soundfont_reverb_chorus: true,
            soundfont_polyphony: 64,
            soundfont_envelope: Default::default(),
            soundfont_quality: Default::default(),
            solfege: None,
        };

        let track2 = TrackState {
            listen: ListenMode::Off,
            id: "track-2".to_string(),
            name: "Audio 2".to_string(),
            track_type: TrackType::Audio,
            ara: None,
            timebase: TrackTimebase::default(),
            parent_group_id: None,
            group_collapsed: false,
            color: crate::theme::Colors::track_color_for_index(1),
            volume: volume::db_to_norm(-6.0),
            volume_effective: volume::db_to_norm(-6.0),
            volume_automation_read: true,
            pan: -0.2,
            muted: false,
            solo: false,
            armed: false,
            input_monitor: InputMonitorMode::Off,
            meter_level_l: 0.42,
            meter_level_r: 0.48,
            meter_peak_hold_l: 0.0,
            meter_peak_hold_r: 0.0,
            meter_clip: false,
            clips: vec![ClipState {
                id: "clip-3".to_string(),
                name: "drums_loop_120.wav".to_string(),
                start_beat: 0.0,
                duration_beats: 16.0,
                source_duration_seconds: None,
                offset_beats: 0.0,
                gain: 1.0,
                clip_type: ClipType::Audio {
                    file_id: "file-drums-loop".to_string(),
                    source_path: None,
                },
                muted: false,
                audio_import: AudioImportState::Ready,
                stretch: AudioClipStretchState::default(),
            }],
            automation_lanes: vec![],
            lane_mode: TrackLaneMode::Clips,
            selected_automation_target: None,
            inserts: Vec::new(),
            sends: Vec::new(),
            routing: TrackRoutingState::for_track_type(TrackType::Audio),
            takes: Vec::new(),
            takes_expanded: false,
            instrument_plugin_instance_id: None,
            builtin_soundfont_player: false,
            soundfont_path: None,
            soundfont_preset: None,
            soundfont_volume: 1.0,
            soundfont_reverb_chorus: true,
            soundfont_polyphony: 64,
            soundfont_envelope: Default::default(),
            soundfont_quality: Default::default(),
            solfege: None,
        };

        let track3 = TrackState {
            listen: ListenMode::Off,
            id: "track-3".to_string(),
            name: "Synth 3".to_string(),
            track_type: TrackType::Midi,
            ara: None,
            timebase: TrackTimebase::default(),
            parent_group_id: None,
            group_collapsed: false,
            color: crate::theme::Colors::track_color_for_index(2),
            volume: volume::db_to_norm(-1.5),
            volume_effective: volume::db_to_norm(-1.5),
            volume_automation_read: true,
            pan: 0.3,
            muted: false,
            solo: false,
            armed: false,
            input_monitor: InputMonitorMode::Off,
            meter_level_l: 0.15,
            meter_level_r: 0.12,
            meter_peak_hold_l: 0.0,
            meter_peak_hold_r: 0.0,
            meter_clip: false,
            clips: vec![ClipState {
                id: "clip-4".to_string(),
                name: "synth_lead.mid".to_string(),
                start_beat: 4.0,
                duration_beats: 8.0,
                source_duration_seconds: None,
                offset_beats: 0.0,
                gain: 1.0,
                clip_type: ClipType::Midi {
                    notes: vec![
                        MidiNoteState::new(60, 0.0, 1.0, 100),
                        MidiNoteState::new(64, 1.0, 1.0, 100),
                        MidiNoteState::new(67, 2.0, 1.0, 100),
                        MidiNoteState::new(72, 3.0, 2.0, 110),
                        MidiNoteState::new(67, 5.0, 1.0, 90),
                        MidiNoteState::new(64, 6.0, 1.0, 90),
                        MidiNoteState::new(60, 7.0, 1.0, 80),
                    ],
                    controller_lanes: Vec::new(),
                    sysex_events: Vec::new(),
                    articulations: Vec::new(),
                },
                muted: false,
                audio_import: AudioImportState::default(),
                stretch: AudioClipStretchState::default(),
            }],
            automation_lanes: vec![],
            lane_mode: TrackLaneMode::Clips,
            selected_automation_target: None,
            inserts: Vec::new(),
            sends: Vec::new(),
            routing: TrackRoutingState::for_track_type(TrackType::Midi),
            takes: Vec::new(),
            takes_expanded: false,
            instrument_plugin_instance_id: None,
            builtin_soundfont_player: false,
            soundfont_path: None,
            soundfont_preset: None,
            soundfont_volume: 1.0,
            soundfont_reverb_chorus: true,
            soundfont_polyphony: 64,
            soundfont_envelope: Default::default(),
            soundfont_quality: Default::default(),
            solfege: None,
        };

        Self {
            bpm: 120.0,
            project_sample_rate: 48_000,
            tempo_map: TempoMap::new(),
            resolved_tempo: ResolvedTempo::default(),
            time_signature_map: TimeSignatureMap::with_default_4_4(),
            time_display_format: TimeDisplayFormat::default(),
            timecode_rate: TimecodeRate::default(),
            project_key: None,
            markers: Vec::new(),
            regions: Vec::new(),
            song_text_events: Vec::new(),
            song_text_index: SongTextIndex::default(),
            song_text_revision: 0,
            time_signature_num: 4,
            time_signature_den: 4,
            viewport: TimelineViewport {
                scroll_x: 0.0,
                scroll_y: 0.0,
                target_scroll_x: 0.0,
                target_scroll_y: 0.0,
                pixels_per_second: 150.0, // Default zoom level in Web UI
                pixels_per_beat: 75.0,
                viewport_width: 0.0,
                viewport_height: 500.0,
                track_area_height: 500.0,
                panel_origin_x: 0.0,
                lane_origin_x_measured: None,
                time_warp: TimeWarp::default(),
            },
            transport: TransportState {
                playing: false,
                recording: false,
                metronome_enabled: false,
                playhead_beats: 2.0,
                loop_enabled: true,
                loop_start_beats: 0.0,
                loop_end_beats: 16.0,
                last_engine_frame: 0,
            },
            tracks: vec![track1, track2, track3],
            audio_connections: crate::audio_connections::AudioConnectionRegistry::new(),
            master_output_connection_id: None,
            monitor_output_connection_id: None,
            output_routing_initialized: false,
            master: MasterBusState {
                volume: volume::db_to_norm(0.0),
                inserts: Vec::new(),
                meter_level_l: 0.0,
                meter_level_r: 0.0,
                meter_peak_hold_l: 0.0,
                meter_peak_hold_r: 0.0,
                meter_clip: false,
                output_label: crate::output_routing::NO_OUTPUT_LABEL.to_string(),
            },
            monitor: MonitorBusState {
                source: MonitorSourceKind::MasterBus,
                source_display: "Master Bus".to_string(),
                output_name: "Out 1-2".to_string(),
                volume: volume::db_to_norm(0.0),
                mute: false,
                dim: false,
                mono: false,
                meter_level_l: 0.0,
                meter_level_r: 0.0,
                meter_peak_hold_l: 0.0,
                meter_peak_hold_r: 0.0,
                meter_clip: false,
                listen_active: false,
                control_room_enabled: true,
            },
            selection: TimelineSelection {
                selected_track_id: Some("track-1".to_string()),
                selected_track_ids: vec!["track-1".to_string()],
                track_selection_anchor_id: Some("track-1".to_string()),
                selected_clip_ids: vec![],
                selected_song_text_event_ids: Vec::new(),
            },
            active_tool: TimelineTool::Pointer,
            snap_to_grid: true,
            grid_division: SnapDivision::Div1_16,
            snap_shape: SnapShape::Straight,
            dragging_track_id: None,
            drag_origin_index: None,
            drag_current_y: 0.0,
            drag_target_index: None,
            follow_playhead: true,
            auto_scroll_mode: AutoScrollMode::Page,
            arrangement_range: None,
            show_tempo_track: true,
            tempo_track_collapsed: false,
            selected_tempo_point_id: None,
            show_time_signature_track: true,
            time_signature_track_collapsed: false,
            selected_time_signature_point_id: None,
            show_song_text_track: false,
            show_region_track: true,
            region_track_collapsed: false,
            selected_region_id: None,
            chord_events: Vec::new(),
            show_chord_track: false,
            chord_track_collapsed: false,
            selected_chord_event_id: None,
            chord_drop_preview: None,
            show_marker_track: true,
            marker_track_collapsed: false,
            selected_marker_id: None,
            global_lane_heights: GlobalLaneHeights::default(),
            global_lane_resize: None,
            global_lane_resize_arm: None,
            track_view_layout: TrackViewLayout::default(),
            track_height_resize: None,
            track_height_resize_arm: None,
            last_touched_plugin_param: None,
            mixer_tree: MixerTreeViewState::default(),
            track_volume_previews: std::collections::HashMap::new(),
            track_volume_gesture_origin: std::collections::HashMap::new(),
            master_volume_preview: None,
            master_volume_gesture_origin: None,
            track_pan_gesture_origin: std::collections::HashMap::new(),
        }
    }

    /// Mutating variant of [`TimelineState::demo_project`]. Seeds the given
    /// state with demo content in-place.
    pub fn seed_demo_content(&mut self) {
        *self = Self::demo_project();
    }
}
