#!/usr/bin/env node
/**
 * Generate app.ftl locale files from SphereUIComponents strings + native-menu.json
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

const menu = JSON.parse(
  fs.readFileSync(path.join(root, "packages/shared/generated/native-menu.json"), "utf8")
);

const menuEntries = [];
function walkMenu(items) {
  for (const item of items || []) {
    if (item.label && item.id) {
      menuEntries.push({ key: "menu." + item.id.replace(/\./g, "-"), en: item.label });
    }
    walkMenu(item.children);
  }
}
for (const m of menu.menus) {
  menuEntries.push({ key: "menu." + m.id, en: m.label });
  walkMenu(m.items);
}

/** @type {[string, string][]} */
const components = [
  ["chrome.project.saved", "Saved"],
  ["chrome.project.unsaved", "Unsaved"],
  ["transport.skip-back", "<<"],
  ["transport.play", ">"],
  ["transport.stop", "[]"],
  ["transport.record", "REC"],
  ["transport.loop", "LOOP"],
  ["transport.metronome", "MET"],
  ["transport.follow", "FOLLOW"],
  ["transport.bpm-label", "BPM"],
  ["transport.time-sig-separator", "/"],
  ["panel.browser", "BROWSER"],
  ["panel.mixer", "MIXER"],
  ["panel.inspector", "INSPECT"],
  ["chrome.import", "IMPORT"],
  ["chrome.save", "SAVE"],
  ["chrome.share", "SHARE"],
  ["chrome.report-bug", "Report bug"],
  ["window.maximize", "MAX"],
  ["window.restore", "RESTORE"],
  ["window.minimize", "-"],
  ["window.close", "X"],
  ["search.projects.placeholder", "Search projects..."],
  ["search.browser.placeholder", "Search..."],
  ["search.plugins.placeholder", "Search plugins..."],
  ["search.plugins-manager.placeholder", "Search plug-ins..."],
  ["search.settings.placeholder", "Search settings..."],
  ["project.default-name", "Untitled Project"],
  ["project.subtitle.saved-locally", "Saved locally"],
  ["project.subtitle.saved", "Saved"],
  ["project.subtitle.unsaved-changes", "Unsaved changes"],
  ["project.subtitle.opened", "Opened"],
  ["project.subtitle.save-failed", "Save failed: { $error }"],
  ["project-switcher.section.this-window", "This Window"],
  ["project-switcher.section.recent", "Recent Projects"],
  ["project-switcher.status.saved", "Saved"],
  ["project-switcher.status.unsaved", "Unsaved"],
  ["project-switcher.empty.no-recent", "No Recent Projects"],
  ["project-switcher.empty.no-match", 'No projects match "{ $query }"'],
  ["wizard.title", "New Project"],
  ["wizard.section.project", "PROJECT"],
  ["wizard.section.template", "TEMPLATE"],
  ["wizard.section.session-settings", "SESSION SETTINGS"],
  ["wizard.section.summary", "SUMMARY"],
  ["wizard.field.name", "Name"],
  ["wizard.field.location", "Location"],
  ["wizard.field.tempo", "Tempo"],
  ["wizard.field.time-signature", "Time Signature"],
  ["wizard.field.beat-grid", "Beat / Grid"],
  ["wizard.field.sample-rate", "Sample Rate"],
  ["wizard.summary.template", "Template"],
  ["wizard.summary.tracks", "Tracks"],
  ["wizard.summary.format", "Format"],
  ["wizard.summary.location", "Location"],
  ["wizard.summary.project", "Project"],
  ["wizard.summary.tracks-value", "{ $audio } audio / { $midi } MIDI"],
  ["wizard.summary.format-value", "{ $bpm } BPM, { $num }/{ $den }, { $khz } kHz"],
  ["wizard.session-settings.hint", "Timing and format for the new session"],
  ["wizard.bpm", "BPM"],
  ["wizard.placeholder.name", "Name"],
  ["wizard.placeholder.bpm", "120"],
  ["wizard.placeholder.location", "~/Documents/Futureboard Studio/Projects"],
  ["wizard.button.browse", "Browse"],
  ["wizard.button.cancel", "Cancel"],
  ["wizard.button.create", "Create Project"],
  ["wizard.footer.hint", "Creates a local Futureboard binary project folder."],
  ["dialog.choose-project-location", "Choose Project Location"],
  ["template.empty.label", "Empty"],
  ["template.recording.label", "Recording"],
  ["template.beat-making.label", "Beat Making"],
  ["template.mixing.label", "Mixing"],
  ["template.scoring.label", "Scoring"],
  ["template.empty.description", "A clean session with the master bus ready."],
  ["template.recording.description", "Audio tracks, monitoring, and record-ready routing."],
  ["template.beat-making.description", "MIDI lanes for drums, bass, keys, and texture."],
  ["template.mixing.description", "Audio channels organized for edit and mix work."],
  ["template.scoring.description", "MIDI-first layout for cues and arrangement sketches."],
  ["template.empty.metadata", "No tracks | 120 BPM"],
  ["template.recording.metadata", "4 audio | 120 BPM"],
  ["template.beat-making.metadata", "4 MIDI | 140 BPM"],
  ["template.mixing.metadata", "8 audio | 120 BPM"],
  ["template.scoring.metadata", "8 MIDI | 120 BPM"],
  ["wizard.error.name-required", "Project name is required."],
  ["wizard.error.location-required", "Choose a project location."],
  ["wizard.error.location-invalid", "Project location is not a valid folder path."],
  ["wizard.error.tempo-range", "Tempo must be between 20 and 300 BPM."],
  ["wizard.error.duplicate", "A project with this name already exists at that location."],
  ["add-track.title", "New Track"],
  ["add-track.hint.bus-route-selected", "Select tracks first to route them into this bus when you create it."],
  ["add-track.hint.return-output", "Return tracks sum into Main by default."],
  ["add-track.kind.audio", "Audio Track"],
  ["add-track.kind.instrument", "Instrument Track"],
  ["add-track.kind.midi", "MIDI Track"],
  ["add-track.kind.plugin", "Plugin Track"],
  ["add-track.kind.bus", "Bus Track"],
  ["add-track.kind.return", "Return Track"],
  ["add-track.kind.group", "Group Track"],
  ["add-track.kind.master", "Master Track"],
  ["add-track.tab.audio", "Audio"],
  ["add-track.tab.instrument", "Inst"],
  ["add-track.tab.midi", "MIDI"],
  ["add-track.tab.plugin", "Plugin"],
  ["add-track.tab.bus", "Bus"],
  ["add-track.tab.return", "Return"],
  ["add-track.tab.group", "Group"],
  ["add-track.tab.master", "Master"],
  ["add-track.tab.automation", "Auto"],
  ["add-track.tab.folder", "Folder"],
  ["add-track.detail.audio", "WAV - MP3 - AIFF"],
  ["add-track.detail.instrument", "VST3 - CLAP - Piano Roll"],
  ["add-track.detail.midi", "Piano Roll - CC"],
  ["add-track.detail.plugin", "VST3 - CLAP"],
  ["add-track.detail.bus", "Sends - Groups"],
  ["add-track.detail.return", "FX Returns - Aux"],
  ["add-track.detail.group", "Sub-mix - Stem"],
  ["add-track.detail.master", "Main Output"],
  ["add-track.description.audio", "Record and arrange audio clips"],
  ["add-track.description.instrument", "MIDI clips routed to an instrument plugin"],
  ["add-track.description.midi", "Sequence instruments with notes"],
  ["add-track.description.plugin", "Host virtual instruments & effects"],
  ["add-track.description.bus", "Route and blend multiple channels"],
  ["add-track.description.return", "Receive sends from other tracks"],
  ["add-track.description.group", "Group and process multiple tracks"],
  ["add-track.description.master", "Final output and master bus"],
  ["add-track.input.all-midi", "All MIDI Inputs"],
  ["add-track.input.system-stereo", "System Input (Stereo)"],
  ["add-track.input.none", "None"],
  ["add-track.badge.ready", "Ready"],
  ["add-track.badge.exists", "Exists"],
  ["add-track.badge.soon", "Soon"],
  ["add-track.section.channels", "Channels"],
  ["add-track.channel.mono", "Mono"],
  ["add-track.channel.stereo", "Stereo"],
  ["add-track.monitor.label", "Monitor"],
  ["add-track.monitor.off", "Off"],
  ["add-track.monitor.auto", "Auto"],
  ["add-track.monitor.in", "In"],
  ["add-track.routing.input", "Input"],
  ["add-track.routing.output", "Output"],
  ["add-track.routing.midi-in", "MIDI In"],
  ["add-track.routing.channel", "Channel"],
  ["add-track.routing.system-input", "System Input"],
  ["add-track.routing.master", "Master"],
  ["add-track.routing.all-channels", "All Channels"],
  ["add-track.arm", "Arm for recording"],
  ["add-track.section.amount", "Amount"],
  ["add-track.button.cancel", "Cancel"],
  ["add-track.button.add-one", "Add Track"],
  ["add-track.button.add-many", "Add { $count } Tracks"],
  ["add-track.summary.plugin-unwired", "Plugin tracks are not wired in Native yet"],
  ["add-track.summary.group-unwired", "Group tracks are not wired in Native yet"],
  ["add-track.summary.master-managed", "Native uses a managed master bus"],
  ["plugin-picker.title", "Add Insert"],
  ["plugin-picker.category.all", "All"],
  ["plugin-picker.empty.filtered", "No plugins match your filter."],
  ["plugin-picker.empty.none", "No scanned plugins found. Insert a stub effect to exercise the chain."],
  ["plugin-picker.stub-effect", "Insert Stub Effect"],
  ["plugin-picker.vendor-category", "{ $vendor } · { $category }"],
  ["plugin.format.vst3", "VST3"],
  ["plugin.format.clap", "CLAP"],
  ["plugin.format.au", "AU"],
  ["plugin.format.lv2", "LV2"],
  ["plugin.format.unknown", "?"],
  ["plugin.stub.display-name", "Stub Effect"],
  ["plugin-manager.title", "Audio Plug-in Manager"],
  ["plugin-manager.details.title", "Plug-in Details"],
  ["plugin-manager.field.name", "Name"],
  ["plugin-manager.field.vendor", "Vendor"],
  ["plugin-manager.field.category", "Category"],
  ["plugin-manager.field.sdk-category", "SDK Category"],
  ["plugin-manager.field.format", "Format"],
  ["plugin-manager.field.kind", "Kind"],
  ["plugin-manager.kind.instrument", "Instrument"],
  ["plugin-manager.kind.effect", "Effect"],
  ["plugin-manager.field.path", "Path"],
  ["plugin-manager.field.class-id", "Class ID"],
  ["plugin-manager.field.version", "Version"],
  ["plugin-manager.field.preset", "Preset"],
  ["plugin-manager.field.status", "Status"],
  ["plugin-manager.status.available", "Available"],
  ["plugin-manager.status.missing-preset", "Missing preset"],
  ["plugin-manager.status.missing", "Missing"],
  ["plugin-manager.action.insert", "Insert on Selected Track"],
  ["plugin-manager.action.editor", "Open Plug-in Editor"],
  ["plugin-manager.action.register", "Validate & Register"],
  ["plugin-manager.action.reveal-preset", "Reveal Preset in Explorer"],
  ["plugin-manager.action.reveal-plugin", "Reveal Plug-in in Explorer"],
  ["plugin-manager.editor.hint", "Editor: VST3 plug-ins with an available preset only."],
  ["plugin-manager.filter.library", "Library"],
  ["plugin-manager.filter.all", "All Plug-ins"],
  ["plugin-manager.filter.kind", "Kind"],
  ["plugin-manager.filter.instruments", "Instruments"],
  ["plugin-manager.filter.effects", "Effects"],
  ["plugin-manager.filter.format", "Format"],
  ["plugin-manager.scan-locations", "Scan Locations"],
  ["plugin-manager.scan-locations.empty", "No scan paths detected"],
  ["plugin-manager.add-location", "+ Add Location"],
  ["plugin-manager.sort.name", "Name"],
  ["plugin-manager.sort.vendor", "Vendor"],
  ["plugin-manager.sort.category", "Category"],
  ["plugin-manager.sort.format", "Format"],
  ["plugin-manager.column.status", "Status"],
  ["plugin-manager.rescan", "Rescan"],
  ["plugin-manager.rescan.scanning", "Scanning…"],
  ["plugin-manager.rescan-all", "Rescan All"],
  ["plugin-manager.ready", "Ready to scan VST3 and CLAP plug-ins."],
  ["plugin-manager.scan.path-errors", "Scan finished with { $n } path error(s)."],
  ["plugin-manager.scan.none-found", "No plug-ins found in scan locations."],
  ["plugin-manager.scan.found-with-errors", "Found { $count } plug-in(s); { $errors } path error(s)."],
  ["plugin-manager.scan.registered", "Registered { $presets } preset(s). { $count } plug-in(s) cached."],
  ["plugin-manager.scan.found", "Found { $count } plug-in(s)."],
  ["plugin-manager.scan.in-progress", "Scanning and registering VST3/CLAP plug-ins…"],
  ["plugin-manager.scan.rescan-all", "Deleting presets and rescanning all plug-ins…"],
  ["plugin-manager.scan.discovering", "Discovering plug-in bundles…"],
  ["plugin-manager.scan.reading", "Reading metadata: { $name }"],
  ["plugin-manager.scan.progress", "Scanning { $current } of { $total } — { $name }"],
  ["plugin-manager.list.scanning", "Scanning… plug-ins will appear here one by one."],
  ["plugin-manager.list.empty", "No cached plug-ins yet. Run Rescan to build the registry."],
  ["plugin-manager.list.no-match", "No plug-ins match the current filter."],
  ["plugin-manager.error.panic", "Scan thread panicked."],
  ["plugin-manager.error.insert-not-connected", "Insert on track: not connected yet."],
  ["plugin-manager.error.editor-not-connected", "Plug-in editor: not connected yet."],
  ["plugin-manager.register.success", "Registered preset for { $name }."],
  ["plugin-manager.register.failed", "Register failed: { $error }"],
  ["settings.title", "Preferences"],
  ["settings.nav.general", "General"],
  ["settings.nav.studio", "Studio"],
  ["settings.nav.workflow", "Workflow"],
  ["settings.nav.interface", "Interface"],
  ["settings.nav.system", "System"],
  ["settings.tab.general", "General"],
  ["settings.tab.audio", "Audio"],
  ["settings.tab.midi", "MIDI"],
  ["settings.tab.recording", "Recording"],
  ["settings.tab.metronome", "Metronome"],
  ["settings.tab.playback", "Playback"],
  ["settings.tab.editing", "Editing"],
  ["settings.tab.appearance", "Appearance"],
  ["settings.tab.plugins", "Plugins"],
  ["settings.tab.files-media", "Files & Media"],
  ["settings.tab.shortcuts", "Key Commands"],
  ["settings.tab.performance", "Performance"],
  ["settings.tab.advanced", "Advanced"],
  ["settings.tab.about", "About"],
  ["settings.tab.general.description", "Application behavior, project defaults, and autosave."],
  ["settings.tab.audio.description", "Driver, devices, sample rate, buffer size, and latency."],
  ["settings.tab.midi.description", "MIDI ports, clock, and external sync."],
  ["settings.tab.recording.description", "Record format and input monitoring."],
  ["settings.tab.metronome.description", "Click volume, sound, and record count-in."],
  ["settings.tab.playback.description", "Transport, looping, and playback behavior."],
  ["settings.tab.editing.description", "Mouse, grid snap, and undo history."],
  ["settings.tab.appearance.description", "Theme, timeline, mixer, and metering display."],
  ["settings.tab.plugins.description", "Scan paths, formats, and plugin hosting."],
  ["settings.tab.files-media.description", "Projects, samples, recordings, and cache locations."],
  ["settings.tab.shortcuts.description", "Keyboard commands and shortcut conflicts."],
  ["settings.tab.performance.description", "Engine load, buffering, and UI responsiveness."],
  ["settings.tab.advanced.description", "Experimental options and developer tools."],
  ["settings.tab.about.description", "Version, licenses, and credits."],
  ["settings.section.application", "Application"],
  ["settings.field.language", "Language"],
  ["settings.field.start-wizard", "Start Wizard"],
  ["settings.show-start-screen", "Show welcome wizard project templates on launch"],
  ["settings.field.update-check", "Update Check"],
  ["settings.check-updates", "Automatically check for software updates"],
  ["settings.section.autosave-backup", "Autosave & Backup"],
  ["settings.field.autosave", "Autosave"],
  ["settings.autosave.enabled", "Automatically save projects periodically"],
  ["settings.field.interval", "Interval"],
  ["settings.interval.minutes", "{ $n } min"],
  ["settings.field.max-backups", "Max Backups"],
  ["settings.section.notifications", "Notifications"],
  ["settings.field.warnings", "Warnings"],
  ["settings.notifications.warnings", "Show warnings on critical errors or file conflicts"],
  ["settings.field.system-notifications", "System Notifications"],
  ["settings.notifications.system", "Send OS system notifications on export finished"],
  ["settings.section.project-defaults", "Project Defaults"],
  ["settings.project-defaults.hint", "Default values applied when creating a new session."],
  ["settings.field.default-tempo", "Default Tempo"],
  ["settings.bpm", "BPM"],
  ["settings.section.audio-engine", "Audio Engine"],
  ["settings.field.backend", "Backend"],
  ["settings.field.input-device", "Input Device"],
  ["settings.field.output-device", "Output Device"],
  ["settings.field.driver-status", "Driver Status"],
  ["settings.driver-status.ready", "Ready"],
  ["settings.section.sample-rate-buffer", "Sample Rate & Buffer"],
  ["settings.field.sample-rate", "Sample Rate"],
  ["settings.sample-rate.hz", "{ $rate } Hz"],
  ["settings.field.buffer-size", "Buffer Size"],
  ["settings.field.round-trip-latency", "Round-trip Latency"],
  ["settings.field.input-latency", "Input Latency"],
  ["settings.field.output-latency", "Output Latency"],
  ["settings.field.round-trip-latency-estimated", "Round-trip Latency (estimated)"],
  ["settings.latency.approx", "~{ $ms } ms"],
  ["settings.buffer.hint", "Lower buffer sizes reduce latency but increase CPU load."],
  ["settings.section.midi-devices", "MIDI Devices"],
  ["settings.field.midi-inputs", "MIDI Inputs"],
  ["settings.midi.keyboard-controller", "Keyboard Controller"],
  ["settings.midi.device-2", "Midi Device 2"],
  ["settings.field.midi-outputs", "MIDI Outputs"],
  ["settings.midi.synth-out", "Synth Out"],
  ["settings.field.midi-clock-sync", "MIDI Clock Sync"],
  ["settings.midi.clock-sync", "Send MIDI clock to output devices"],
  ["settings.section.sync-external-clock", "Sync & External Clock"],
  ["settings.field.clock-source", "Clock Source"],
  ["settings.clock.internal", "Internal"],
  ["settings.clock.midi", "MIDI"],
  ["settings.field.ltc-reader", "LTC Reader"],
  ["settings.ltc.enable", "Enable linear timecode (LTC) reader on input"],
  ["settings.backend.wasapi-shared", "WASAPI Shared"],
  ["settings.backend.wasapi-exclusive", "WASAPI Exclusive"],
  ["settings.backend.asio", "ASIO"],
  ["settings.device.builtin-mic", "Built-in Microphone"],
  ["settings.device.speakers-realtek", "Speakers (Realtek)"],
  ["settings.section.theme-interface", "Theme & Interface"],
  ["settings.field.theme-preset", "Theme Preset"],
  ["settings.theme.fleet-dark", "Fleet Dark"],
  ["settings.theme.ableton-dark", "Ableton Dark"],
  ["settings.field.ui-scale", "UI Scale"],
  ["settings.ui-scale.value", "{ $scale }x"],
  ["settings.section.timeline", "Timeline"],
  ["settings.field.grid-intensity", "Grid Intensity"],
  ["settings.grid-intensity.percent", "{ $n }%"],
  ["settings.section.piano-roll", "Piano Roll"],
  ["settings.field.key-guides", "Key Guides"],
  ["settings.piano-roll.key-guides", "Show piano key guides in background"],
  ["settings.section.mixer-metering", "Mixer & Metering"],
  ["settings.field.meter-decay", "Meter Decay"],
  ["settings.meter-decay.dbs", "{ $n } dB/s"],
  ["settings.field.peak-hold", "Peak Hold"],
  ["settings.peak-hold.seconds", "{ $n } s"],
  ["settings.section.editing-mouse", "Editing > Mouse & Navigation"],
  ["settings.field.zoom-sensitivity", "Zoom Sensitivity"],
  ["settings.field.natural-scroll", "Natural Scroll"],
  ["settings.natural-scroll", "Invert trackpad/mousewheel scroll direction"],
  ["settings.section.editing-snap", "Editing > Grid & Snap"],
  ["settings.field.snap-to-grid", "Snap to Grid"],
  ["settings.snap-to-grid", "Snap clips/notes to current grid lines"],
  ["settings.field.default-snap", "Default Snap"],
  ["settings.section.editing-history", "Editing > History"],
  ["settings.field.max-undo-steps", "Max Undo Steps"],
  ["settings.section.recording-audio-format", "Recording > Audio Format"],
  ["settings.field.format-type", "Format Type"],
  ["settings.format.wav", "WAV"],
  ["settings.format.aiff", "AIFF"],
  ["settings.format.flac", "FLAC"],
  ["settings.field.bit-depth", "Bit Depth"],
  ["settings.bit-depth.16", "16-bit"],
  ["settings.bit-depth.24", "24-bit"],
  ["settings.bit-depth.32-float", "32-bit float"],
  ["settings.section.recording-metronome", "Recording > Metronome Click"],
  ["settings.section.metronome", "Metronome"],
  ["settings.field.enable-click", "Enable Click"],
  ["settings.metronome.enable", "Hear metronome click during recording & playback"],
  ["settings.field.click-volume", "Click Volume"],
  ["settings.field.click-sound", "Click Sound"],
  ["settings.metronome.woodblock", "Woodblock"],
  ["settings.metronome.beep", "Beep"],
  ["settings.field.enable-count-in", "Count-in"],
  ["settings.metronome.count-in", "Play click bars before recording starts"],
  ["settings.field.count-in-bars", "Count-in Bars"],
  ["settings.count-in.bars", "bars"],
  ["settings.section.playback-transport", "Playback > Transport"],
  ["settings.field.spacebar-action", "Spacebar Action"],
  ["settings.spacebar.play-pause", "Play / Pause"],
  ["settings.spacebar.play-stop-soon", "Play / Stop"],
  ["settings.field.return-to-start", "Return to Start"],
  ["settings.return-on-stop", "Return playhead to start position on Stop"],
  ["settings.section.rendering", "Rendering"],
  ["settings.rendering.hint", "Choose how the timeline is drawn. GPU Acceleration uses WGPU when available; CPU Render forces the GPUI paint fallback (best compatibility)."],
  ["settings.field.renderer", "Renderer *"],
  ["settings.field.gpu-device", "GPU Device *"],
  ["settings.field.status", "Status"],
  ["settings.renderer.gpu", "GPU Acceleration"],
  ["settings.renderer.cpu", "CPU Render"],
  ["settings.gpu.auto", "Auto"],
  ["settings.gpu.cpu-active", "CPU Render active (GPUI paint fallback)."],
  ["settings.gpu.none-detected", "No GPU adapter detected. CPU Render fallback will be used."],
  ["settings.gpu.ready", "GPU Acceleration ready — { $n } adapter(s) detected."],
  ["settings.gpu.enum-failed", "GPU enumeration failed. CPU Render fallback is available."],
  ["settings.restart-required", "* Restart Futureboard Studio to apply this change."],
  ["settings.section.plugins-formats", "Plugins > Formats & Folders"],
  ["settings.field.formats", "Formats"],
  ["settings.plugins.enable-vst3", "Enable VST3"],
  ["settings.plugins.enable-clap", "Enable CLAP"],
  ["settings.plugins.background-scan", "Background Scan"],
  ["settings.field.vst3-folders", "VST3 Folders"],
  ["settings.field.clap-folders", "CLAP Folders"],
  ["settings.field.actions", "Actions"],
  ["settings.plugins.scan-now", "Scan Plugins Now"],
  ["settings.button.reveal", "Reveal"],
  ["settings.about.title", "Futureboard Studio"],
  ["settings.about.version", "Futureboard Studio / Mochi DAW v0.1.0"],
  ["settings.about.built-with", "Built with GPUI, Rust, and C++ VST3 SDK."],
  ["settings.about.copyright", "© 2026 Futureboard Studio team. All rights reserved."],
  ["settings.placeholder.files-media", "Project folders, sample libraries…"],
  ["settings.placeholder.shortcuts", "Search, edit, and reset keyboard commands…"],
  ["settings.placeholder.advanced", "Experimental features, developer tools…"],
  ["settings.scaffold.not-wired", "This section is scaffolded for future settings."],
  ["settings.empty.tab-not-wired", "The { $tab } panel is not fully wired in Native yet."],
  ["settings.empty.no-search-match", 'No settings match "{ $query }"'],
  ["settings.language.en", "en"],
  ["settings.language.fr", "fr"],
  ["context.timeline.add-audio", "Add Audio Track"],
  ["context.timeline.add-midi", "Add MIDI Track"],
  ["context.paste", "Paste"],
  ["context.zoom-in", "Zoom In"],
  ["context.zoom-out", "Zoom Out"],
  ["context.clip.rename", "Rename"],
  ["context.clip.duplicate", "Duplicate"],
  ["context.clip.delete", "Delete"],
  ["context.clip.split-at-playhead", "Split at Playhead"],
  ["context.clip.reveal-browser", "Reveal in Browser"],
  ["context.clip.unavailable", "Clip unavailable"],
  ["context.track.rename", "Rename Track"],
  ["context.track.duplicate", "Duplicate Track"],
  ["context.track.delete", "Delete Track"],
  ["context.track.mute", "Mute"],
  ["context.track.solo", "Solo"],
  ["context.track.arm", "Arm"],
  ["context.browser.open-folder", "Open Folder"],
  ["context.browser.open", "Open"],
  ["context.browser.reveal", "Reveal in Explorer/Finder"],
  ["context.browser.refresh", "Refresh"],
  ["context.browser.new-folder", "New Folder"],
  ["context.browser.rename", "Rename"],
  ["context.browser.copy-path", "Copy Path"],
  ["context.browser.import", "Import to Timeline"],
  ["context.project.open", "Open Project"],
  ["context.browser.no-selection", "No file selected"],
  ["context.mixer.reset-volume", "Reset Volume"],
  ["context.mixer.reset-pan", "Reset Pan"],
  ["browser.root.current-project", "Current Project"],
  ["browser.root.project-prefix", "PROJECT: { $name }"],
  ["browser.category.audio-files", "Audio Files"],
  ["browser.category.plugins", "Plug-ins"],
  ["browser.category.instruments", "Instruments"],
  ["browser.category.projects", "Projects"],
  ["browser.category.samples", "Samples"],
  ["browser.category.user-library", "User Library"],
  ["browser.loading", "Loading…"],
  ["browser.error.cannot-read", "Cannot read folder"],
  ["browser.panel.title", "BROWSER"],
  ["browser.selection.none", "No file selected"],
  ["browser.selection.label", "SEL"],
  ["browser.file.unavailable", "unavailable"],
  ["inspector.title", "Inspector"],
  ["inspector.no-selection.title", "No Selection"],
  ["inspector.no-selection.hint", "Select a track or clip"],
  ["inspector.section.track", "TRACK"],
  ["inspector.field.type", "Type"],
  ["inspector.track-type.audio", "Audio"],
  ["inspector.track-type.midi", "MIDI"],
  ["inspector.track-type.instrument", "Instrument"],
  ["inspector.track-type.bus", "Bus"],
  ["inspector.track-type.return", "Return"],
  ["inspector.track-type.master", "Master"],
  ["inspector.field.volume", "Volume"],
  ["inspector.volume.db", "{ $db } dB"],
  ["inspector.field.pan", "Pan"],
  ["inspector.pan.center", "Center"],
  ["inspector.pan.left", "L { $percent }"],
  ["inspector.pan.right", "R { $percent }"],
  ["inspector.field.clips", "Clips"],
  ["inspector.section.state", "STATE"],
  ["inspector.badge.mute", "M"],
  ["inspector.badge.solo", "S"],
  ["inspector.badge.record", "R"],
  ["inspector.badge.input", "I"],
  ["inspector.section.clip", "CLIP"],
  ["inspector.clip.type", "Type"],
  ["inspector.clip.type.audio", "Audio"],
  ["inspector.clip.type.midi", "MIDI"],
  ["inspector.clip.track", "Track"],
  ["inspector.clip.start", "Start"],
  ["inspector.clip.start.beats", "{ $value } bt"],
  ["inspector.clip.length", "Length"],
  ["mixer.title", "Mixer"],
  ["mixer.section.inserts", "INSERTS"],
  ["mixer.section.sends", "SENDS"],
  ["mixer.insert.empty", "empty"],
  ["mixer.track-type.audio", "AUDIO"],
  ["mixer.track-type.midi", "MIDI"],
  ["mixer.track-type.instrument", "INST"],
  ["mixer.track-type.bus", "BUS"],
  ["mixer.track-type.return", "RTN"],
  ["mixer.track-type.master", "MST"],
  ["mixer.channel", "CH{ $nn }"],
  ["mixer.master.label", "Master"],
  ["mixer.master.bus-label", "MST·BUS"],
  ["mixer.stereo", "STEREO"],
  ["mixer.output.1-2", "OUT 1-2"],
  ["insert.slot.empty", "Empty"],
  ["bottom-panel.tab.mixer", "Mixer"],
  ["bottom-panel.tab.editor", "Editor"],
  ["bottom-panel.tab.effect-editor", "Effect Editor"],
  ["bottom-panel.mix-level", "Mix: 80%"],
  ["bottom-panel.plugin.equalizer", "Equalizer"],
  ["bottom-panel.plugin.compressor", "Compressor"],
  ["bottom-panel.plugin.delay", "Delay Unit"],
  ["timeline.tool.select", "Select [V]"],
  ["timeline.tool.draw", "Draw [P]"],
  ["timeline.tool.cut", "Cut [C]"],
  ["timeline.tool.glue", "Glue [G]"],
  ["timeline.tool.mute", "Mute [U]"],
  ["timeline.tool.stretch", "Stretch [T]"],
  ["timeline.tool.automation", "Automation [A]"],
  ["timeline.snap.auto", "Auto"],
  ["timeline.snap.off", "Off"],
  ["timeline.snap.1-bar", "1 bar"],
  ["track-header.type.audio", "AUD"],
  ["track-header.type.midi", "MID"],
  ["track-header.type.instrument", "INS"],
  ["track-header.type.bus", "BUS"],
  ["track-header.type.return", "RTN"],
  ["track-header.type.master", "MAS"],
  ["track-header.clips", "CH { $nn } · { $n } clips"],
  ["clip.imported-audio", "Imported Audio"],
  ["status.ready", "Ready"],
  ["status.playing", "Playing"],
  ["status.audio-ready", "Audio ready"],
  ["status.audio-error", "Audio: { $error }"],
  ["status.audio-offline", "Audio offline"],
  ["status.audio-info", "{ $rate } Hz  { $backend }  Latency: { $ms } ms"],
  ["status.fps", "{ $fps } fps  { $ms } ms"],
  ["dialog.save-project-as", "Save Project As"],
  ["dialog.save-copy", "Save Copy"],
  ["dialog.open-project", "Open Project"],
  ["dialog.filter.futureboard-project", "Futureboard Project"],
  ["error.audio-engine-unavailable", "audio engine unavailable"],
  ["error.plugin-instantiate-failed", "Plugin failed to instantiate"],
  ["error.create-project-folder", "Failed to create project folder: { $e }"],
  ["error.save-initial-project", "Failed to save initial project file: { $e }"],
  ["error.update-studio-window", "Unable to update the main studio window: { $error }"],
  ["project.file.missing", "Missing"],
  ["edit.cut", "Cut"],
  ["edit.copy", "Copy"],
  ["edit.paste", "Paste"],
  ["edit.select-all", "Select All"],
  ["project.error.io", "I/O error: { $e }"],
  ["project.error.invalid-magic", "Not a Futureboard project file"],
  ["project.error.unsupported-version", "Unsupported project version: { $v }"],
  ["project.error.corrupted", "Corrupted project: { $msg }"],
  ["project.error.checksum", "Checksum mismatch: expected { $expected }, got { $got }"],
];

// Build unified entry map (menu first, then components; components override duplicates)
const entries = new Map();
for (const e of menuEntries) entries.set(e.key, e.en);
for (const [key, en] of components) entries.set(key, en);

const sortedKeys = [...entries.keys()].sort();

function escapeFtlValue(s) {
  // Fluent multiline / special chars
  if (s.includes("\n")) {
    return '"""\n' + s + '\n"""';
  }
  return s;
}

function writeFtl(locale, getValue) {
  const lines = [
    `# Futureboard Studio — ${locale}`,
    `# Extracted from SphereUIComponents + native-menu.json`,
    `# Generated: ${new Date().toISOString().slice(0, 10)}`,
    "",
    "## Application Menu",
    "",
  ];

  let lastSection = "## Application Menu";
  for (const key of sortedKeys) {
    let section = "## Components";
    if (key.startsWith("menu.")) section = "## Application Menu";
    else if (key.startsWith("settings.")) section = "## Settings";
    else if (key.startsWith("wizard.") || key.startsWith("template.") || key.startsWith("add-track.")) section = "## Dialogs";
    else if (key.startsWith("plugin")) section = "## Plugins";
    else if (key.startsWith("context.")) section = "## Context Menus";
    else if (key.startsWith("browser.") || key.startsWith("search.")) section = "## Browser";
    else if (key.startsWith("inspector.") || key.startsWith("mixer.") || key.startsWith("timeline.") || key.startsWith("track-header.") || key.startsWith("bottom-panel.") || key.startsWith("panel.")) section = "## Panels & Timeline";
    else if (key.startsWith("status.") || key.startsWith("error.") || key.startsWith("dialog.") || key.startsWith("project.")) section = "## Status & Errors";
    else if (key.startsWith("chrome.") || key.startsWith("transport.") || key.startsWith("window.")) section = "## App Chrome";

    if (section !== lastSection) {
      lines.push("", section, "");
      lastSection = section;
    }
    const value = getValue(key, entries.get(key));
    lines.push(`${key} = ${escapeFtlValue(value)}`);
  }

  const outPath = path.join(root, `packages/shared/locales/${locale}/app.ftl`);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, lines.join("\n") + "\n", "utf8");
  console.log(`Wrote ${outPath} (${sortedKeys.length} keys)`);
}

// Write en-US (source)
writeFtl("en-US", (_key, en) => en);

console.log(`Total keys: ${sortedKeys.length}`);
